name: Build with Home Clean

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: pmatos/action-home-clean@master
      - uses: actions/checkout@v2
      - run: echo Hello World 
